name: Build Executables

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        arch: [amd64, 386]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21.4

    - name: Install GLFW
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get install -y libglfw3-dev

    - name: Install GLFW
      if: matrix.os == 'macos-latest'
      run: brew install glfw

    - name: Install GLFW
      if: matrix.os == 'windows-latest'
      run: |
        choco install glfw

    - name: Build
      run: |
        GOOS=$(echo ${{ matrix.os }} | sed 's/-latest//')
        GOARCH=${{ matrix.arch }}
        OUTPUT_NAME=shimoExporter-${GOOS}-${GOARCH}
        export CGO_ENABLED=1 && go mod init shimoExporter && go mod tidy && go build -o $OUTPUT_NAME ./app/main.go

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }}-${{ matrix.arch }}
        path: shimoExporter-${{ matrix.os }}-${{ matrix.arch}} 
